# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='short',
            field=models.CharField(default='lol', max_length=15),
            preserve_default=False,
        ),
    ]
