# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortenedurl_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
